config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'issue#index'
  resources :user
  resources :group, only: [:new, :create, :edit, :update] do
    resources :issue
    resources :category, only: [:new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :issue
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_tree

  # has_many :children, class_name: :Category, foreign_key: :parent_id
  # belongs_to :parent, class_name: :Category
  belongs_to :group

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :categories
  
  validates :password, length: { in: 6..10 }
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :stocks
  has_many :likes
  has_many :issues

  #S3保存用に設定
  has_one_attached :image

  #サインアップ時の制限
  validates :name, presence: true
  validates :password, length:{maximum: 20}
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception #???
  # before_action :authenticate_user! #
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  # before_action :group_params

  # def new
  # end

  def create
    # binding.pry
    if category_params[:division] == "1"
      @category = Category.create(category_params) #@category = @group.categories.new(category_params)と一緒の意味
      if @category.save
        redirect_to new_group_issue_path(group_params)
      else
        # redirect_to new_group_issue_path(group_params), alert: '保存に失敗しました'
      end
    end


    # if @category.parent_id != nil
    # if @category.name(category_params) != @category2.name(category_params2)
    # binding.pry
    # @category3 = @category2.children.create(category_params3)
    # child.children.create(category_params)
    # root = Category.create
    # binding.pry
    # return if @category.parent_id == nil
    if category_params[:division] == "2"
      @category2 = Category.create(category_params)
      if @category2.save
        redirect_to new_group_issue_path(group_params)
      else
        # redirect_to new_group_issue_path(group_params), alert: '保存に失敗しました'
      end
    end

  end

  private
  def category_params
    params.require(:category).permit(:name, :parent_id, :division).merge(group_id: group_params.id)
  end

  def group_params
    @group = Group.find(params[:group_id])
  end

end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  # before_action :set_group

  def new
    @group = Group.new
    @my_group = Group.where(user_id: current_user.id)
  end

  def create
    Group.create(name: group_params[:name],password: group_params[:password], user_id: current_user.id)
    redirect_to new_group_path
  end

  def favorite_group
    set_group
  end

  private
  def group_params
    params.require(:group).permit(:name, :password)
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/issue_controller.rb
class IssueController < ApplicationController
  # before_action :group_params

  def index
  end

  def new
    @issue = Issue.new
    @group = Group.new
    @category = Category.new
    @category2 = Category.new
    @large_categories = Category.roots.where(group_id: group_params[:id])
    @middle_categories = Category.where(group_id: group_params[:id], division: 2)
    # @middle_categories = Category.メソッド.where(group_id: group_params[:id]) #『メソッド』の所に中カテゴリを抽出するメソッドかく
    # @small_categories = Category.メソッド.where(group_id: group_params[:id]) #『メソッド』の所に小カテゴリを抽出するメソッドかく
  end

  def create
  end

  # def move_index
  #   redirect_to action: :index unless user_signed_in?
  # end
  private
  def group_params
    Group.find(params[:group_id])
  end

  def issue_params
    params.require(:issue).permit(:title, :text, :small_tag, :middle_tag, :large_tag).merge(group_id: group_params.id)
  end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/group/new.html.haml
= render 'layouts/header-logined'
= form_for @group, url: group_index_path, class: "group__first" do |t|
  .group
    .group-content
      .group__title
        .group__title-new.target 新規グループ作成
        .group__title-edit.target グループ編集
        .group__title-favorite.target マイグループ
      .group-content__form
        .group__first
          .group-form
            .group-form__left
              = t.label :name, 'グループ名'
            .group-form__right
              = t.text_field :name,class: "group-form__right-area", placeholder: "グループ名を入力してください"

          .group-form
            .group-form__left
              = t.label :password, 'パスワード'
            .group-form__right
              = t.password_field :password,class: "group-form__right-area",placeholder: "6文字以上10文字以内"

          .group-form-btn
            = t.submit "登録", class: "btn"

        .group__second
          .group-show
            - @my_group.each do |p|
              .issues__main__item
                =link_to "#" do
                  = image_tag "umihebi.png", class: "issues__main__item__user-image"
                .issues__main__item__right
                  .issues__main__item__right-title
                    = link_to new_group_issue_path(p) do
                      = p.name
                  .issues__main__item__right-info
                    .right-info__user.inline
                      作成者：
                      %span
                        = link_to "#" do
                          = p.user.name
                    .right-info__time.inline
                      %span 作成日：
                      = time_ago_in_words(p.created_at)

app/views/issue/_issues__group-ranking.html.haml
.issues__ranking
  .issues__ranking__top
    .issues__ranking__top__left.inline
      %p グループ ランキング
    .issues__ranking__top__right.inline
      .ra__date.week
        = link_to "#" do
          週間
      .ra__date.month
        = link_to "#" do
          月間
      .ra__date.all
        = link_to "#" do
          全て

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline
        = fa_icon 'trophy', class: "ra__count-one"
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline
        = fa_icon 'trophy', class: "ra__count-two"
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline
        = fa_icon 'trophy', class: "ra__count-three"
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline.num
        ３
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline.num
        ４
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline.num
        ５
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

app/views/issue/_issues__item-box.html.haml
.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        How to 速度改善 ーWebパフォーマンスについて知っておきたいこと7選ー
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        [git] gitconfigで会社用アカウントと個人用アカウントを楽に使い分けする
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        AWS導入前に知っておきたかった「AWSアカウント設計」
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        How to 速度改善 ーWebパフォーマンスについて知っておきたいこと7選ー
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        [git] gitconfigで会社用アカウントと個人用アカウントを楽に使い分けする
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        AWS導入前に知っておきたかった「AWSアカウント設計」
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        How to 速度改善 ーWebパフォーマンスについて知っておきたいこと7選ー
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        [git] gitconfigで会社用アカウントと個人用アカウントを楽に使い分けする
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        AWS導入前に知っておきたかった「AWSアカウント設計」
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        How to 速度改善 ーWebパフォーマンスについて知っておきたいこと7選ー
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        [git] gitconfigで会社用アカウントと個人用アカウントを楽に使い分けする
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

.issues__main__item
  =link_to "#" do
    = image_tag "umihebi.png", class: "issues__main__item__user-image"
  .issues__main__item__right
    .issues__main__item__right-title
      = link_to "#" do
        AWS導入前に知っておきたかった「AWSアカウント設計」
    .issues__main__item__right-info
      .right-info__user.inline
        by
        %span
          = link_to "#" do
            Umihebi
      .right-info__time.inline
        ２ days ago
      .right-info__like.inline
        = fa_icon('thumbs-o-up')
        %span 18

app/views/issue/_issues__user-ranking.html.haml
.issues__ranking
  .issues__ranking__top
    .issues__ranking__top__left.inline
      %p ユーザー ランキング
    .issues__ranking__top__right.inline
      .ra__date.week
        = link_to "#" do
          週間
      .ra__date.month
        = link_to "#" do
          月間
      .ra__date.all
        = link_to "#" do
          全て

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline
        = fa_icon 'trophy', class: "ra__count-one"
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline
        = fa_icon 'trophy', class: "ra__count-two"
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline
        = fa_icon 'trophy', class: "ra__count-three"
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline.num
        ３
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline.num
        ４
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

  .issues__ranking__user
    .issues__ranking__user-content.inline
      .ra__count.inline.num
        ５
      .ra__icon.inline
        = link_to "#" do
          = image_tag "umihebi.png", class: "mini"
      .ra__user.inline
        .ra__user-nickname
          = link_to "#" do
            %span Umihebi
    .issues__ranking__user-num.inline
      .ra__number 400
      %p Contributions

app/views/issue/_large__category-content.html.haml
.large-category
  %a.large-category__list{"data-category-id" => "${category.id}", "data-category-name" => "${category.name}"}
    = category_name


-# .middle_category
-#   %ul
-#     %li
-#       = category_name
-#
-# .small_category
-#   %ul
-#     %li
-#       = category_name

app/views/issue/_middle__category-content.html.haml
.large_category
  = category_name

app/views/issue/index.html.haml
= render 'layouts/header-logined'

.issues.clearfix
  .issues__navi
    %ul
      %li.issues__navi__list
        = link_to "#", class: "issue__navi__list-link" do
          = fa_icon('line-chart')
          トレンド
      %li.issues__navi__list
        = link_to "#", class: "issue__navi__list-link" do
          = fa_icon('list')
          タイムライン
      %li.issues__navi__list
        = link_to "#", class: "issue__navi__list-link" do
          = fa_icon('tags')
          タグフィード
      %li.issues__navi__list
        = link_to "#", class: "issue__navi__list-link" do
          = fa_icon('star')
          マイルストーン


  .issues__main
    .issues__main__top
      .issues__main__top__title
        .issues__main__top__title__left
          %span
            = fa_icon('line-chart')
          %span トレンド
        .issues__main__top__title__right
          %p 最近人気の記事を表示

      .issues__main__top__date
        = link_to "#" do
          １日
        = link_to "#" do
          週間
        = link_to "#" do
          月間

    = render 'issues__item-box'

  = render 'issues__user-ranking'

  = render 'issues__group-ranking'

app/views/issue/new.html.haml
= render 'layouts/header-logined'

.issue__new
  .issue__new-content
    .issue__new-content-left
      .issue__new-content-left__top.clearfix
        %p 見たまま
        %p HTML
        %p プレビュー
      .issue__new-content-left__title
        = text_field :name, class: "issue__new-content-left__title-logo", placeholder: "タイトル"
      .issue__new-content-left__category
        大カテ＞
        中カテ＞
        小カテ
      .issue__new-content-left__text
        = text_field :text, placeholder: "本文"
    .issue__new-content-nav
      %ul
        %li
          = fa_icon('folder')
        %li
          = fa_icon('picture-o')
        %li
          = fa_icon('cog')
        %li
          = fa_icon('file')
        %li
          = fa_icon('plus')

    = form_for [@group, @category], url: group_category_index_path do |c|
      .issue__new-content-right
        .issue__new-content-right__title 大カテゴリー
        .issue__new-content-right__list
          .issue__new-content-right__list-search
            = c.text_field :name, class: "issue__new-content-right__list-search-area", placeholder: "検索"
          .issue__new-content-right__list-btn
            %span
              = fa_icon('plus')
            新規作成
          .issue__new-content-right__list-new
            = c.text_field :name, class: "issue__new-content-right__list-new-area", placeholder: "カテゴリー名"
            = c.hidden_field :division, :value => 1
            .issue__new-content-right__list-new-btn
              = c.submit "登録", class: "btn"

        .issue__new-content-right__category
          - if @large_categories
            - @large_categories.each do |t|
              = render partial: 'large__category-content', locals: {category_name: t.name, category_group: t.group.name}

    = form_for [@group, @category2], url: group_category_index_path do |c|
      .issue__new-content-right
        .issue__new-content-right__title 中カテゴリー
        .issue__new-content-right__list
          .issue__new-content-right__list-search
            = c.text_field :name, class: "issue__new-content-right__list-search-area", placeholder: "検索"
          .issue__new-content-right__list-btn
            %span
              = fa_icon('plus')
            新規作成
          .issue__new-content-right__list-new
            = c.text_field :name, class: "issue__new-content-right__list-new-area", placeholder: "カテゴリー名"
            = c.hidden_field :division, :value => 2
            -# = c.hidden_field :parent_id, :value => ? #ここに大カテゴリーのidを取得
            .large-category__id

            .issue__new-content-right__list-new-btn
              = c.submit "登録", class: "btn"

        .issue__new-content-right__category
          - if @middle_categories
            - @middle_categories.each do |t|
              = render partial: 'middle__category-content', locals: {category_name: t.name, category_group: t.group.name}

app/views/layouts/_header-logined.html.haml
%heaedr.header
  .header__content.clearfix

    .header__content__logo
      = link_to root_path, class: "white" do
        = image_tag "umihebi.png"
        %h3.pyonpyon eeigel

    .header__right
      .menu
        %ul
          %li
            %input.header__right__textfield{:name => "keyword", :placeholder => "キーワードから探す", :type => "text"}
          %li
            = link_to "#", class: "btn" do
              %span
                = fa_icon('file')
              ストック

          .btn.tweet
            %span
              = fa_icon('pencil')
            投稿する
            %ul.tweet-menu.inline
              %li.tweet-menu__item
                = link_to new_group_path do
                  グループ
              %li.tweet-menu__item
                = link_to "#" do
                  個人
          %li
            .btn.info
              %span
                = fa_icon('bell')
              ０
            .info-menu
              .info-menu__top.clearfix
                .info-menu__top__left
                  %span
                    = fa_icon('bell-o')
                    お知らせ
                .info-menu__top__right
                  = link_to "通知設定", "#"
              .info-menu__content.clearfix
              .info-menu__bottom
                = link_to "通知一覧をみる", "#"

      .icon
        = image_tag "umihebi.png"
        %i
          = fa_icon 'caret-down', class: "caret-down"
        %ul.user-menu.inline
          %li.user-menu__item
            = link_to "#" do
              マイページ
          %li.user-menu__item
            = link_to "#" do
              下書き一覧
          %li.user-menu__item
            = link_to "#" do
              設定
          %li.user-menu__item
            = link_to "#" do
              ヘルプ
          %li.user-menu__item
            = link_to "ログアウト", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FindAnError
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield